name: 'Build, Pack, Push'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-pack-push:
    name: Build, Pack, Push
    uses: n3oltd/workflows/.github/workflows/dotnet-build-pack-push.yml@main
    with:
      run-tests: false
      run-pack: true